######################################################################
# Automatically generated by qmake (3.0) Mon Feb 26 10:28:19 2018
######################################################################

TEMPLATE = app
TARGET = Qt
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT+=widgets